# Site settings
title: CEASA Online
email:
description: Cotação dos preços dos produtos vendidos nos Centros de Abastecimento (CEASA) em todo o Brasil

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "http://ceasa.online" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 2973388149
data-ad-client: ca-pub-9204963049240271
google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-34891480-15"
addthis_id: ra-5644da281510c62f
disqus_account: jeky-new-age

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: facebook
    url: https://https://www.facebook.com/CEASAOnline
  - title: instagram
    url: https://instagram.com/ceasaonlineapp

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
